services:
  local-gpss:
    build:
      context: .
      target: ${BUILD_TARGET:-not-configured}
      args:
        UPDATE_LEGALITY: ${UPDATE_LEGALITY:-false}
        PKHEX_TAG: ${PKHEX_TAG:-unused}
    container_name: local-gpss
    ports:
      - "8082:8082"
    volumes:
      - ./:/app/host
    environment:
      - LEGALITY_ONLY=${LEGALITY_ONLY:-0}
    restart: unless-stopped
